### ISSUE TITLE
Lists not parsed

### ISSUE THREAD

**Issue by HadrienRenaud** [YoPox/mdConvert#10]
Problem with lists parsing.

The syntax for list is, for me :
```markdown
Ceci est du texte

- premier élément
- deuxième élément
 
Ceci est du texte.
```
which should render :
```latex
Ceci est du texte
\begin{itemize}
\item premier élément
\item second élément
\end{itemize}
Ceci est du texte.
```
 And finally display :
Ceci est du texte

- premier élément
- deuxième élément
 
Ceci est du texte.

This doesn't parse correctly with the newest version of mdConvert.

**Comment by yopox** [comment]
Haha why are you still using mdConvert ?
One idea would be to roll back to the first implementation where basic features seemed working 🎃

**Comment by elidiot18** [comment]
One other idea would be to adapt current mdbg2tex which is perfectly fine and correct. It would allow more than the former version, for instance multi lists, a more accurate way of parsing bold italic etc. It could be adapted in a few minutes

**Comment by HadrienRenaud** [comment]
An other idea would be to seriously implement the md2mdbg file. The md2tex
file would be really simple after...

**Comment by elidiot18** [comment]
Done

**Comment by HadrienRenaud** [comment]
And [mdbg](https://github.com/YoPox/mdbg) can now convert directly md to tex ...
